#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("APPDroid.Framework.Resource", IsApplication=false)]

namespace APPDroid.Framework
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public static int ColorAzul = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int ColorBlanco = 2130968576;
			
			// aapt resource value: 0x7f040004
			public static int ColorGrisLeve = 2130968580;
			
			// aapt resource value: 0x7f040001
			public static int ColorNegro = 2130968577;
			
			// aapt resource value: 0x7f040003
			public static int ColorRojo = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public static int Tamano_10 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Tamano_12 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int activity_horizontal_margin = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int activity_vertical_margin = 2131034115;
			
			// aapt resource value: 0x7f050009
			public static int ancho_icon = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public static int ancho_icon_config = 2131034125;
			
			// aapt resource value: 0x7f050007
			public static int card_primary_text_size = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int card_secondary_text_size = 2131034120;
			
			// aapt resource value: 0x7f050010
			public static int config_credenciales = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public static int config_padding = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public static int config_servicios = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public static int largo_icon = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public static int largo_icon_config = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public static int login_padding = 2131034123;
			
			// aapt resource value: 0x7f050004
			public static int project_card_min_height = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int project_card_min_width = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int project_card_padding = 2131034118;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int actualizar_a = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int actualizar_d = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int actualizar_n = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int button_custom_actua = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int button_custom_consultar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int button_custom_pendiente = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int button_custom_save = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int button_custom_settings = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int completado_a = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int completado_d = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int completado_n = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int configurar_a = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int configurar_d = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int configurar_n = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int consultar_a = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int consultar_d = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int consultar_n = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int eliminar_a = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int eliminar_d = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int eliminar_n = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int gradient = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int guardar_a = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int guardar_d = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int guardar_n = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int ic_action_cancel = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int ic_action_overflow = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int ic_action_save = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int ic_action_settings = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int ic_admed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int ic_agci = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int ic_aut = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int ic_carmed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int ic_devmed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int ic_hc = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int ic_invfis = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int ic_logo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int ic_movart = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int ic_rpt = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int ic_sca = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int ic_sum = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int icon_actualizar = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public static int no_cargar_a = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public static int no_cargar_d = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public static int no_cargar_n = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public static int pendiente_a = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public static int pendiente_d = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public static int pendiente_n = 2130837551;
			
			// aapt resource value: 0x7f020030
			public static int radius_codigo_barras = 2130837552;
			
			// aapt resource value: 0x7f020031
			public static int radius_left = 2130837553;
			
			// aapt resource value: 0x7f020032
			public static int radius_rignt = 2130837554;
			
			// aapt resource value: 0x7f020033
			public static int rounded_corner = 2130837555;
			
			// aapt resource value: 0x7f020034
			public static int sombras = 2130837556;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public static int EadNombre = 2131296257;
			
			// aapt resource value: 0x7f090000
			public static int listViewEad = 2131296256;
			
			// aapt resource value: 0x7f090002
			public static int menu_incosistencias_framework = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int app_select_master = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int items_master = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public static int menu_framework = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public static int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f06002c
			public static int action_websearch = 2131099692;
			
			// aapt resource value: 0x7f060031
			public static int app_admed = 2131099697;
			
			// aapt resource value: 0x7f060032
			public static int app_agci = 2131099698;
			
			// aapt resource value: 0x7f060038
			public static int app_aut = 2131099704;
			
			// aapt resource value: 0x7f060033
			public static int app_carmed = 2131099699;
			
			// aapt resource value: 0x7f060035
			public static int app_devmed = 2131099701;
			
			// aapt resource value: 0x7f060034
			public static int app_hc = 2131099700;
			
			// aapt resource value: 0x7f060036
			public static int app_invfis = 2131099702;
			
			// aapt resource value: 0x7f06003a
			public static int app_movart = 2131099706;
			
			// aapt resource value: 0x7f06002d
			public static int app_not_available = 2131099693;
			
			// aapt resource value: 0x7f060037
			public static int app_rpt = 2131099703;
			
			// aapt resource value: 0x7f060039
			public static int app_sum = 2131099705;
			
			// aapt resource value: 0x7f060040
			public static int btn_aceptar = 2131099712;
			
			// aapt resource value: 0x7f060042
			public static int btn_activar = 2131099714;
			
			// aapt resource value: 0x7f060045
			public static int btn_borrar = 2131099717;
			
			// aapt resource value: 0x7f060041
			public static int btn_cancelar = 2131099713;
			
			// aapt resource value: 0x7f060047
			public static int btn_confirmacion = 2131099719;
			
			// aapt resource value: 0x7f060043
			public static int btn_desactivar = 2131099715;
			
			// aapt resource value: 0x7f060044
			public static int btn_eliminar = 2131099716;
			
			// aapt resource value: 0x7f060046
			public static int btn_ingresar = 2131099718;
			
			// aapt resource value: 0x7f060048
			public static int btn_ver = 2131099720;
			
			// aapt resource value: 0x7f060071
			public static int code_device = 2131099761;
			
			// aapt resource value: 0x7f06003d
			public static int codigo_cliente = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public static int contrasena_cliente = 2131099710;
			
			// aapt resource value: 0x7f06002b
			public static int drawer_close = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public static int drawer_open = 2131099690;
			
			// aapt resource value: 0x7f060004
			public static int edit_password = 2131099652;
			
			// aapt resource value: 0x7f060003
			public static int edit_usuario = 2131099651;
			
			// aapt resource value: 0x7f06006b
			public static int fecha_dispositivo = 2131099755;
			
			// aapt resource value: 0x7f060072
			public static int hit_code_device = 2131099762;
			
			// aapt resource value: 0x7f06006d
			public static int hit_codigo_cliente = 2131099757;
			
			// aapt resource value: 0x7f06003b
			public static int licenciamiento = 2131099707;
			
			// aapt resource value: 0x7f06002f
			public static int menu_acerca = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public static int menu_configurar = 2131099694;
			
			// aapt resource value: 0x7f060030
			public static int menu_salir = 2131099696;
			
			// aapt resource value: 0x7f060002
			public static int panel_control = 2131099650;
			
			// aapt resource value: 0x7f06006f
			public static int password_text = 2131099759;
			
			// aapt resource value: 0x7f06000f
			public static int randoHoras = 2131099663;
			
			// aapt resource value: 0x7f06003c
			public static int servicios = 2131099708;
			
			// aapt resource value: 0x7f060049
			public static int spnn_servicio = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public static int spnn_ubicacion = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public static int textView_especialidad = 2131099723;
			
			// aapt resource value: 0x7f060073
			public static int text_generar = 2131099763;
			
			// aapt resource value: 0x7f06006c
			public static int text_licenciamiento = 2131099756;
			
			// aapt resource value: 0x7f060070
			public static int text_services = 2131099760;
			
			// aapt resource value: 0x7f060074
			public static int text_sub = 2131099764;
			
			// aapt resource value: 0x7f060067
			public static int txt_Valida_codigo_dar = 2131099751;
			
			// aapt resource value: 0x7f06005f
			public static int txt_administracion_med = 2131099743;
			
			// aapt resource value: 0x7f06001a
			public static int txt_administrar = 2131099674;
			
			// aapt resource value: 0x7f060051
			public static int txt_alertas = 2131099729;
			
			// aapt resource value: 0x7f060012
			public static int txt_almacen = 2131099666;
			
			// aapt resource value: 0x7f060059
			public static int txt_aplicacion_json = 2131099737;
			
			// aapt resource value: 0x7f06000e
			public static int txt_buscar = 2131099662;
			
			// aapt resource value: 0x7f060065
			public static int txt_cama_v_final = 2131099749;
			
			// aapt resource value: 0x7f060064
			public static int txt_cama_v_inicial = 2131099748;
			
			// aapt resource value: 0x7f06000d
			public static int txt_camas = 2131099661;
			
			// aapt resource value: 0x7f06001c
			public static int txt_campo_separador = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public static int txt_camposrequeridos = 2131099675;
			
			// aapt resource value: 0x7f060060
			public static int txt_cargos = 2131099744;
			
			// aapt resource value: 0x7f06005b
			public static int txt_cerrar_sesion = 2131099739;
			
			// aapt resource value: 0x7f06004c
			public static int txt_cliente = 2131099724;
			
			// aapt resource value: 0x7f060009
			public static int txt_cliente_user = 2131099657;
			
			// aapt resource value: 0x7f06005c
			public static int txt_cmoadmmed = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public static int txt_cmocarmed = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public static int txt_cmodevmed = 2131099742;
			
			// aapt resource value: 0x7f06000b
			public static int txt_codigo_barra = 2131099659;
			
			// aapt resource value: 0x7f060018
			public static int txt_codigo_barra_requerido = 2131099672;
			
			// aapt resource value: 0x7f06004f
			public static int txt_codigo_servicio = 2131099727;
			
			// aapt resource value: 0x7f060068
			public static int txt_completar_medicamento = 2131099752;
			
			// aapt resource value: 0x7f060005
			public static int txt_configuracion = 2131099653;
			
			// aapt resource value: 0x7f060050
			public static int txt_configuracionConexion = 2131099728;
			
			// aapt resource value: 0x7f060053
			public static int txt_configuracion_ingreso = 2131099731;
			
			// aapt resource value: 0x7f060010
			public static int txt_confirmacion = 2131099664;
			
			// aapt resource value: 0x7f060056
			public static int txt_des_serializada = 2131099734;
			
			// aapt resource value: 0x7f060000
			public static int txt_desea_cancelar = 2131099648;
			
			// aapt resource value: 0x7f060061
			public static int txt_devoluciones = 2131099745;
			
			// aapt resource value: 0x7f060058
			public static int txt_error = 2131099736;
			
			// aapt resource value: 0x7f060057
			public static int txt_error_servicio = 2131099735;
			
			// aapt resource value: 0x7f060016
			public static int txt_escanear_historia = 2131099670;
			
			// aapt resource value: 0x7f060054
			public static int txt_estructura_admin = 2131099732;
			
			// aapt resource value: 0x7f060011
			public static int txt_fuente = 2131099665;
			
			// aapt resource value: 0x7f060022
			public static int txt_historia_inco = 2131099682;
			
			// aapt resource value: 0x7f060025
			public static int txt_historia_requerida = 2131099685;
			
			// aapt resource value: 0x7f06005a
			public static int txt_login_app = 2131099738;
			
			// aapt resource value: 0x7f06001f
			public static int txt_medicament = 2131099679;
			
			// aapt resource value: 0x7f060027
			public static int txt_msn = 2131099687;
			
			// aapt resource value: 0x7f060062
			public static int txt_no_especiales = 2131099746;
			
			// aapt resource value: 0x7f060019
			public static int txt_no_especiality = 2131099673;
			
			// aapt resource value: 0x7f060021
			public static int txt_numbre_historia = 2131099681;
			
			// aapt resource value: 0x7f060024
			public static int txt_obligatorio_texto = 2131099684;
			
			// aapt resource value: 0x7f060069
			public static int txt_obligatorio_texto_fuente = 2131099753;
			
			// aapt resource value: 0x7f060015
			public static int txt_pacientes_con_ordenes = 2131099669;
			
			// aapt resource value: 0x7f06004d
			public static int txt_password = 2131099725;
			
			// aapt resource value: 0x7f060020
			public static int txt_patient_no_list = 2131099680;
			
			// aapt resource value: 0x7f060028
			public static int txt_rango_desde = 2131099688;
			
			// aapt resource value: 0x7f060029
			public static int txt_rango_hasta = 2131099689;
			
			// aapt resource value: 0x7f060052
			public static int txt_salirApp = 2131099730;
			
			// aapt resource value: 0x7f060063
			public static int txt_select_especialidad = 2131099747;
			
			// aapt resource value: 0x7f060007
			public static int txt_server = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public static int txt_servicio = 2131099660;
			
			// aapt resource value: 0x7f060013
			public static int txt_servicio2 = 2131099667;
			
			// aapt resource value: 0x7f060006
			public static int txt_servinte = 2131099654;
			
			// aapt resource value: 0x7f060017
			public static int txt_solicitar_firma = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public static int txt_superar_2 = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public static int txt_superior_4 = 2131099677;
			
			// aapt resource value: 0x7f060023
			public static int txt_titulo_validacion = 2131099683;
			
			// aapt resource value: 0x7f060014
			public static int txt_ubicacion = 2131099668;
			
			// aapt resource value: 0x7f06004e
			public static int txt_url = 2131099726;
			
			// aapt resource value: 0x7f060055
			public static int txt_usuario_ead = 2131099733;
			
			// aapt resource value: 0x7f060066
			public static int txt_valida_rango = 2131099750;
			
			// aapt resource value: 0x7f06000a
			public static int txt_validar = 2131099658;
			
			// aapt resource value: 0x7f060026
			public static int txt_variable_configuracion = 2131099686;
			
			// aapt resource value: 0x7f060008
			public static int txt_ver = 2131099656;
			
			// aapt resource value: 0x7f06006e
			public static int url_services_d = 2131099758;
			
			// aapt resource value: 0x7f06003f
			public static int url_servicios = 2131099711;
			
			// aapt resource value: 0x7f06006a
			public static int version_dispositivo = 2131099754;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070003
			public static int DetallePosologia = 2131165187;
			
			// aapt resource value: 0x7f070006
			public static int Detalle_Paciente = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int Detalle_Posologia = 2131165191;
			
			// aapt resource value: 0x7f070000
			public static int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070005
			public static int NombrePaciente = 2131165189;
			
			// aapt resource value: 0x7f070009
			public static int TextoActionMedicamentos = 2131165193;
			
			// aapt resource value: 0x7f070002
			public static int TextoBlanco = 2131165186;
			
			// aapt resource value: 0x7f070001
			public static int TextoBlancoMenu = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public static int TextoDetallePaciente = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public static int TextoListaPacienteNombre = 2131165194;
			
			// aapt resource value: 0x7f070004
			public static int TotalmenteBlanco = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public static int detallePatients = 2131165196;
			
			// aapt resource value: 0x7f070008
			public static int items_grids = 2131165192;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
